// front/front-angular/src/app/editar/editar.component.ts
import { Component, OnInit } from '@angular/core';
import * as $ from 'jquery';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { ComentarioService } from '../service/comentario.service';
import { Router } from '@angular/router';
import swal from'sweetalert2';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-editar',
  templateUrl: './editar.component.html',
  styleUrls: ['./editar.component.css']
})
export class EditarComponent implements OnInit {

  fcomentario = new FormGroup({
    id: new FormControl('', Validators.required),
    nombre: new FormControl('',Validators.required),
    correo: new FormControl('',Validators.required),
    asunto: new FormControl('',Validators.required),
    comentario: new FormControl('',Validators.required),
  });

  constructor(private service: ComentarioService,private router: Router) {

  }

  updateComments(){


    Swal.fire({
      title: 'Actualizar comentario?',
      text: 'Estas seguro que deseas actualizar el comentario?',
      showCancelButton: true,
      confirmButtonText: 'Si',
      cancelButtonText:'No'
    }).then((result) => {
      if (result.isConfirmed) {
        console.log("Estas seguro que deseas actualizar el comentario?");
        console.log(this.fcomentario.value);
        this.service.update(this.fcomentario.value).subscribe((result) =>{
          console.log(result.data);
          Swal.fire('Comentario Actualizado', '', 'success');
          this.router.navigate(['listar']);
        });
      } else if (result.isDismissed) {
        this.router.navigate(['index']);
      }
    })
  }
  ngOnInit(): void {

    console.log("############");
    console.log(this.service.comentario);

    this.fcomentario.patchValue({
      id:this.service.comentario[0].id,
      nombre:this.service.comentario[0].nombre,
      correo: this.service.comentario[0].correo,
      asunto: this.service.comentario[0].asunto,
      comentario: this.service.comentario[0].comentario
    });
  }

}

<div class="card center">
    <div
      id="btncomments"
      class="button-block button-blue margin-top margin-top-3"
    >
    Editar Comentario
    </div>

    <div id="formulario" class="container">
      <h4><b>Editar Comentario</b></h4>

        <form [formGroup]="fcomentario" (ngSubmit)="updateComments()">
        <input hidden type="text" formControlName="id" />
        <label for="label">Nombre</label>
        <input required  placeholder="Ingrese su nombre" type="text" formControlName="nombre" />
        <label for="label">Correo</label>
        <input required  type="email" placeholder="Ingrese su correo" formControlName="correo" />
        <label for="label">Asunto</label>
        <input required  type="text" placeholder="Ingrese asunto" formControlName="asunto" />
        <label for="label">Comentario</label>
        <input required  type="text" placeholder="Comentario"formControlName="comentario" />
        <button onclick="location.href='http://127.0.0.1:8000/comentarios'" class="button button-orange margin-min"> <i
          class="fa-solid fa-angle-left"></i> Volver</button>
        <button type="submit" class="button button-blue margin-top-1 margin-bottom-3" href="">
          Agregar
        </button>
      </form>
    </div>
  </div>

// front/front-react/src/components/Editar.js
import "../public/css/Editar.css";
import React, { useEffect, useState } from "react";
import { Getbyid } from "../services/CommentServices";
import { ModelComentario } from "../models/Comentario";
import { useParams } from "react-router-dom";
import { updateComments } from "../services/CommentServices";
import {BrowserRouter as Router, Link} from 'react-router-dom';
import "../public/css/navbar.css";

function Editar() {
  const { id } = useParams();
  const [Comentario, setComentario] = useState(ModelComentario());

  useEffect(() => {
    Getbyid(id).then((result) => {
      setComentario(result[0]);
    });
  }, [id]);

  const handleChange = (event) => {
    const name = event.target.name;
    const value = event.target.value;
    setComentario({ ...Comentario, [name]: value });
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    updateComments(Comentario);
  };

  return (


    <React.Fragment>



    <div id="body-index" class="margin-top-3">
      <div class="center">
        <div class="card center">
          <div id="btncomments" class="button button-block button-pink" href="">
            Actualizar Comentario
          </div>
          <div id="formularioEdit" class="container margin-top-1">
            <form onSubmit={handleSubmit}>
              <input
                required
                hidden
                //placeholder="Ingrese su nombre"
                type="text"
                name="id"
                value={Comentario.id || ""}
                onChange={handleChange}
              />
              <label>Nombre</label>
              <input
                required
                //placeholder="Ingrese su nombre"
                type="text"
                name="nombre"
                value={Comentario.nombre || ""}
                onChange={handleChange}
              />
              <label>Correo</label>
              <input
                required
                type="text"
                name="correo"
                placeholder="Ingrese su correo"
                value={Comentario.correo || ""}
                onChange={handleChange}
              />
              <label>Asunto</label>
              <input
                required
                type="text"
                name="asunto"
                placeholder="Ingrese asunto"
                value={Comentario.asunto || ""}
                onChange={handleChange}
              />
              <label>Comentario</label>
              <input
                required
                type="text"
                name="comentario"
                placeholder="Comentario"
                value={Comentario.comentario || ""}
                onChange={handleChange}
              />
              <div>
              <Link to="/">
                <button
                  class="button button-orange margin-min"> <i class="fa-solid fa-angle-left"></i> Volver 
                </button> 
                </Link>
                <button
                  type="submit"
                  className="button button-blue margin-top-1 margin-bottom-3"
                >
                  Guardar <i class="fa-solid fa-floppy-disk"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    </React.Fragment>
  );
}

export default Editar;
